export const data = [
    {
        id: 338953,
        overview: "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
        poster_path: "https://image.tmdb.org/t/p/w1280/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
        release_date: "2022-04-06",
        title: "Fantastic Beasts: The Secrets of Dumbledore",
        vote_average: 6.8,
    },
    {
        id: 752623,
        overview: "A reclusive romance novelist was sure nothing could be worse than getting stuck on a book tour with her cover model until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
        poster_path: "https://image.tmdb.org/t/p/w1280/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
        release_date: "2022-03-24",
        title: "The Lost City",
        vote_average: 6.7,
    },
    {
        id: 675353,
        overview: "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
        poster_path: "https://image.tmdb.org/t/p/w1280/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
        release_date: "2022-03-30",
        title: "Sonic the Hedgehog 2",
        vote_average: 7.8,
    },
    {
        id: 818397,
        overview: "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
        poster_path: "https://image.tmdb.org/t/p/w1280/QaNLpq3Wuu2yp5ESsXYcQCOpUk.jpg",
        release_date: "2022-04-28",
        title: "Memory",
        vote_average: 7.2,
    },
    {
        id: 639933,
        overview: "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
        poster_path: "https://image.tmdb.org/t/p/w1280/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg",
        release_date: "2022-04-07",
        title: "The Northman",
        vote_average: 7.3,
    },
    {
        id: 507086,
        overview: "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
        poster_path: "https://image.tmdb.org/t/p/w1280/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
        release_date: "2022-06-01",
        title: "Jurassic World Dominion",
        vote_average: 6.8,
    },
    {
        id: 335787,
        overview: "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
        poster_path: "https://image.tmdb.org/t/p/w1280/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
        release_date: "2022-02-10",
        title: "Uncharted",
        vote_average: 7.2,
    },
    {
        id: 634649,
        overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        poster_path: "https://image.tmdb.org/t/p/w1280/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        release_date: "2021-12-15",
        title: "Spider-Man: No Way Home",
        vote_average: 8.1,
    },
    {
        id: 414906,
        overview: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
        poster_path: "https://image.tmdb.org/t/p/w1280/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        release_date: "2022-03-01",
        title: "The Batman",
        vote_average: 7.8,
    },
    {
        id: 629542,
        overview: "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
        poster_path: "/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
        release_date: "2022-03-17",
        title: "The Bad Guys",
        vote_average: 7.8,
    }
]